/** T11 plan wire types. The compiled inventory is generated by the host, never accepted from HTTP input. */
export type ModuleActionKind = 'add' | 'update' | 'enable' | 'disable' | 'remove' | 'configure' | 'integration';

export interface ModuleChoiceActionV1 {
  readonly kind: ModuleActionKind;
  readonly moduleId: string;
  /** Identifies an exact candidate already present in CompiledModuleInventoryV1. */
  readonly candidateKey?: string;
  /** Required on add/enable only; [] explicitly selects headless operation. */
  readonly audiences?: readonly ('admin' | 'app')[];
  readonly dependencyId?: string;
  readonly settingId?: string;
  /** Reference to server-owned configuration; never a secret value. */
  readonly valueRef?: string;
  readonly enabled?: boolean;
}

export interface ModulePlanBaseV1 {
  /** Zero is the initial state before the singleton head exists. */
  readonly revision: number;
  readonly compositionDigest: string;
  readonly lockDigest: string;
  readonly inventoryDigest: string;
}

/** At most 32 actions and 8 KiB of canonical UTF-8 JSON. */
export interface ModuleChoiceV1 {
  readonly schemaVersion: 1;
  readonly base: ModulePlanBaseV1;
  readonly actions: readonly ModuleChoiceActionV1[];
}

export interface CompiledModuleCandidateV1 {
  readonly candidateKey: string;
  readonly moduleId: string;
  readonly origin: string;
  readonly version: string;
  readonly source: Readonly<{kind: 'workspace'; path: string} | {kind: 'package'; name: string}>;
  /** T02 descriptor and exact lock node validated against available artifact bytes at build time. */
  readonly descriptor: Readonly<Record<string, unknown>>;
  readonly lockNode: Readonly<Record<string, unknown>>;
}

export interface CompiledModuleInventoryV1 {
  readonly schemaVersion: 1;
  readonly digest: string;
  readonly candidates: readonly CompiledModuleCandidateV1[];
}

export interface ModuleDiagnosticV1 {
  readonly code: string;
  readonly path: string;
  readonly message: string;
}

export interface ModulePlanChangeV1 {
  readonly moduleId: string;
  readonly action: string;
}

/** Compact, persistent projection; at most 8 KiB of canonical UTF-8 JSON. */
export interface ModulePlanSummaryV1 {
  readonly status: 'ready' | 'blocked';
  readonly changes: readonly ModulePlanChangeV1[];
  readonly dependencyOrder: readonly string[];
  readonly disabledContributionCount: number;
  readonly diagnosticCount: number;
  readonly detailsPaged: boolean;
}

/** Full proposal is transient. Persist only canonical choices/summary and their digests. */
export interface ModulePlanV1 {
  readonly schemaVersion: 1;
  readonly base: ModulePlanBaseV1;
  readonly inventoryDigest: string;
  readonly choicesDigest: string | null;
  readonly next: Readonly<{composition: Readonly<Record<string, unknown>>;
    lock: Readonly<Record<string, unknown>>}> | null;
  readonly nextCompositionDigest: string | null;
  readonly nextLockDigest: string | null;
  readonly summary: ModulePlanSummaryV1;
  readonly summaryDigest: string;
  readonly diagnostics: readonly ModuleDiagnosticV1[];
}

export interface ModulePlanCurrentV1 {
  readonly composition: Readonly<Record<string, unknown>>;
  readonly lock: Readonly<Record<string, unknown>>;
  readonly descriptors: readonly Readonly<Record<string, unknown>>[];
  readonly revision: number;
}

export const MODULE_PLAN_LIMITS = Object.freeze({actions: 32, choicesBytes: 8 * 1024,
  summaryBytes: 8 * 1024, dataPlanBytes: 48 * 1024});
