/** Opaque credentials; only their purpose-bound digest belongs in persistent storage. */
const prefixes = {
  session: 'cz1s_',
  'api-token': 'cz1a_',
  invitation: 'cz1i_',
  activation: 'cz1v_',
  'password-reset': 'cz1r_',
  bootstrap: 'cz1b_',
} as const;

export type TokenPurpose = keyof typeof prefixes;
export interface IssuedToken {
  /** Deliver once through the intended channel. Never log or persist this value. */
  readonly token: string;
  readonly digest: string;
}

const encoder = new TextEncoder();
function prefixFor(purpose: TokenPurpose): string {
  if (typeof purpose !== 'string' || !Object.hasOwn(prefixes, purpose)) throw new TypeError('Unknown token purpose.');
  return prefixes[purpose];
}
function base64url(bytes: Uint8Array): string {
  return btoa(String.fromCharCode(...bytes)).replaceAll('+', '-').replaceAll('/', '_').replace(/=+$/, '');
}

/** Malformed, noncanonical or cross-purpose credentials are rejected before hashing. */
export async function digestOpaqueToken(value: unknown, purpose: TokenPurpose): Promise<string | null> {
  const prefix = prefixFor(purpose);
  if (typeof value !== 'string' || value.length !== prefix.length + 43 || !value.startsWith(prefix)) return null;
  const encoded = value.slice(prefix.length);
  if (!/^[A-Za-z0-9_-]{43}$/.test(encoded)) return null;
  const bytes = Uint8Array.from(atob(encoded.replaceAll('-', '+').replaceAll('_', '/') + '='), char => char.charCodeAt(0));
  if (bytes.length !== 32 || base64url(bytes) !== encoded) return null;
  const digest = new Uint8Array(await crypto.subtle.digest('SHA-256', encoder.encode(`creezio:credential:v1:${purpose}:${value}`)));
  return `sha256:${Array.from(digest, byte => byte.toString(16).padStart(2, '0')).join('')}`;
}

/** 256 random bits, generated by the host's Web Crypto implementation. */
export async function issueOpaqueToken(purpose: TokenPurpose): Promise<IssuedToken> {
  const prefix = prefixFor(purpose);
  const token = prefix + base64url(crypto.getRandomValues(new Uint8Array(32)));
  const digest = await digestOpaqueToken(token, purpose);
  if (!digest) throw new Error('Unable to encode credential.');
  return Object.freeze({ token, digest });
}
