import {readFileSync,writeFileSync,mkdirSync,existsSync,lstatSync,readdirSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {isCompositionSchemaPlan,schemaDigest} from '../data/composition-schema.mjs';

const root=fileURLToPath(new URL('../../',import.meta.url));
const normalized=sql=>sql.trim().replace(/;$/,'').trimEnd();
function assertSafePath(value,kind) {
  const absolute=path.resolve(value);
  for(let cursor=absolute;;cursor=path.dirname(cursor)){
    const stat=lstatSync(cursor,{throwIfNoEntry:false});
    if(stat&&(stat.isSymbolicLink()||(cursor===absolute
      ? kind==='directory'&&!stat.isDirectory()||kind==='file'&&!stat.isFile()
      : !stat.isDirectory())))
      throw new Error('Linked or non-regular Sites paths are refused.');
    if(cursor===path.dirname(cursor))break;
  }
  return absolute;
}
function safeDirectory(value) {
  const absolute=assertSafePath(value,'directory');
  mkdirSync(absolute,{recursive:true});return assertSafePath(absolute,'directory');
}
function safeFile(value) {return assertSafePath(value,'file');}
function assertSafeTree(directory) {
  for(const name of readdirSync(directory)){
    const entry=path.join(directory,name),stat=lstatSync(entry);
    if(stat.isSymbolicLink()||(!stat.isDirectory()&&!stat.isFile()))
      throw new Error('Linked or non-regular Sites paths are refused.');
    if(stat.isDirectory())assertSafeTree(entry);
  }
}
const json=file=>JSON.parse(readFileSync(safeFile(file),'utf8'));
const write=(file,value)=>writeFileSync(safeFile(file),typeof value==='string'?value:JSON.stringify(value,null,2)+'\n');

/** Drizzle owns the deployment journal. Its custom-DDL envelope retains the approved compiler's
 * checks and WITHOUT ROWID definitions, which a second ORM model compiler would otherwise change.
 * Only additive CREATEs are supported here; existing applied files are never rewritten.
 */
export function prepareSitesSchema(plan,output,{drizzleCli=path.join(root,'node_modules/drizzle-kit/bin.cjs')}={}) {
  if(!isCompositionSchemaPlan(plan))throw new Error('An approved central composition schema is required.');
  const target=safeDirectory(output),db=safeDirectory(path.join(target,'db'));
  // Drizzle initializes its own directories and journal on the first generation.
  const drizzle=assertSafePath(path.join(target,'drizzle'),'directory');
  assertSafePath(path.join(drizzle,'meta'),'directory');
  if(existsSync(drizzle))assertSafeTree(drizzle);
  const historyPath=path.join(db,'creezio-schema-history.json');
  const previous=existsSync(historyPath)?json(historyPath):null;
  if(previous&&previous.applicationId!==plan.applicationId)throw new Error('Sites schema belongs to another application.');
  for(const item of previous?.files??[]){
    if(!/^(?:drizzle\/)[A-Za-z0-9_./-]+$/.test(item.path)||item.path.split('/').includes('..')
      ||schemaDigest(readFileSync(safeFile(path.join(target,item.path)),'utf8'))!==item.digest)
      throw new Error('An existing generated schema artifact changed; inspect before publication.');
  }
  const retained=previous?.objects??[],byName=new Map(retained.map(o=>[o.name,o])),additions=[];
  for(const object of plan.objects){
    const old=byName.get(object.name);
    if(old&&(old.type!==object.type||old.table!==object.table||normalized(old.sql)!==normalized(object.sql)))
      throw new Error(`Existing schema object changed: ${object.name}. A centrally reviewed evolution is required.`);
    if(!old)additions.push(object);
  }
  const objects=[...retained,...additions].map(o=>({...o,sql:normalized(o.sql)}));
  const schemaPath=path.join(db,'schema.ts');
  const source='// Generated from Creezio current model declarations. Do not author a parallel ORM schema.\n'
    +'// Deployment uses Drizzle custom DDL generated by the central Creezio compiler.\n'
    +`export const currentModelDeclarations = ${JSON.stringify({host:plan.host,modules:plan.runtimeCatalog.modules},null,2)} as const;\n`;
  write(schemaPath,source);
  const config=path.join(target,'drizzle.config.cjs');
  write(config,"module.exports={dialect:'sqlite',schema:'./db/schema.ts',out:'./drizzle'};\n");
  let migration=null,files=[...(previous?.files??[])];
  if(additions.length){
    const journal=path.join(drizzle,'meta/_journal.json');
    const before=existsSync(journal)?json(journal).entries:[];
    execFileSync(process.execPath,[drizzleCli,'generate','--custom','--name',`creezio_${plan.modelDigest.slice(7,19)}`,'--config',config],
      {cwd:target,encoding:'utf8',timeout:30_000,stdio:['ignore','pipe','pipe'],windowsHide:true});
    assertSafePath(drizzle,'directory');
    assertSafePath(path.join(drizzle,'meta'),'directory');
    assertSafeTree(drizzle);
    const next=json(journal).entries;
    if(next.length!==before.length+1||JSON.stringify(next.slice(0,-1))!==JSON.stringify(before))throw new Error('Unexpected Drizzle journal change.');
    const entry=next.at(-1);if(!/^[A-Za-z0-9_-]+$/.test(entry.tag))throw new Error('Invalid Drizzle entry.');
    migration=`drizzle/${entry.tag}.sql`;
    const sql='-- Generated centrally from current Creezio declarations; schema only.\n'
      +additions.map(o=>normalized(o.sql)+';').join('\n--> statement-breakpoint\n')+'\n';
    write(path.join(target,migration),sql);
    files=files.filter(f=>f.path!=='drizzle/meta/_journal.json');
    const snapshot=`drizzle/meta/${String(entry.idx).padStart(4,'0')}_snapshot.json`;
    for(const relative of [migration,snapshot,'drizzle/meta/_journal.json'])if(existsSync(path.join(target,relative)))
      files.push({path:relative,digest:schemaDigest(readFileSync(safeFile(path.join(target,relative)),'utf8'))});
  }
  const history={schemaVersion:1,applicationId:plan.applicationId,compositionDigest:plan.compositionDigest,
    modelDigest:plan.modelDigest,objects,files};
  write(historyPath,history);
  return {migration,addedObjects:additions.length,retainedObjects:retained.length,objects,
    digest:schemaDigest(objects),historyPath};
}
